---
title: "luad_tcga"
output: html_document
date: "2024-04-09"
---

###### (1) Setting up working environment
```{r setup}
knitr::opts_knit$set(root.dir = normalizePath("C:/Users/Owner/Documents/USC/Senior Year/qbio490/qbio490_sp24_final_luad"))

library(BiocManager)
library(TCGAbiolinks)
library(maftools)
```

###### (2) Query and retrieve the TCGA lung adenocarcinoma clinical data
```{r}
# retrieve TCGA-LUAD clinical data
clin_query <- GDCquery(project = "TCGA-LUAD",
                       data.category = "Clinical",
                       data.type = "Clinical Supplement",
                       data.format = "BCR Biotab")
GDCdownload(clin_query)
clinical.BCRtab.all <- GDCprepare(clin_query)
```

Saving dataframes to eventually push to GitHub
```{r}
# base clinical data
luad_clinic <- clinical.BCRtab.all$clinical_patient_luad[-c(1,2),]
colnames(luad_clinic)[colnames(luad_clinic) == "bcr_patient_barcode"] <- "Tumor_Sample_Barcode"
write.csv(luad_clinic, "C:/Users/Owner/Documents/USC/Senior Year/qbio490/qbio490_sp24_final_luad/luad_clinical_data.csv")

# base drug data
luad_drug <- clinical.BCRtab.all$clinical_drug_luad[-c(1,2),]
colnames(luad_drug)[colnames(luad_drug) == "bcr_patient_barcode"] <- "Tumor_Sample_Barcode"
write.csv(luad_drug, "C:/Users/Owner/Documents/USC/Senior Year/qbio490/qbio490_sp24_final_luad/luad_drug_data.csv")

luad_rad <- clinical.BCRtab.all$clinical_radiation_luad[-c(1,2),]
colnames(luad_rad)[colnames(luad_rad) == "bcr_patient_barcode"] <- "Tumor_Sample_Barcode"
write.csv(luad_rad, "C:/Users/Owner/Documents/USC/Senior Year/qbio490/qbio490_sp24_final_luad/luad_radiation_data.csv")
```

